---
# Name of the website
# Defaults to the title (see below)
site_name: "AwesomeDocs"

# URL where the site will live
site_url: "https://awesomedocs.traction.one"

# Title of the website
title: "AwesomeDocs"

# Description of the website
description: "An awesome documentation site generator made with Gatsby! So, inherently, it's blazing fast!"

# URL to the logo of your site
logo: "https://github.com/AwesomeDocs.png"

# Link to, say GitHub issues, where users can send feedback
feedback: "https://github.com/AwesomeDocs/website/issues"

# Copyright notice that would be placed in the footer
copyright: "Copyright 2019 - AwesomeDocs"


# Accent color of the site
# Default: `#3eb0ef`
color: ""


# List of links that will be shown in the header
# This is just an example structure
# You can modify it any way you like
links:
  - name: "GitHub"
    link: "https://github.com/AwesomeDocs"


# Structure for sidebar navigation
# This is just an example structure
# You can modify it any way you like
navigation:
  - section: "Intro"
    links:
        - name: "Home"
          link: "/"
  - section: "Getting Started"
    links:
      - name: "Install"
        link: "/install"
      - name: "Usage"
        link: "/usage"
  - section: "Reference Guides"
    links:
      - name: "CLI Tool"
        link: "/cli"
      - name: "Configuration"
        link: "/config"
  - section: "Other"
    links:
      - name: "Getting Support"
        link: "/support"
